FROM bitnami/airflow-scheduler:latest
ADD airflow.cfg /opt/bitnami/airflow
#USER root
#RUN apt update
#RUN apt install -y iputils-ping
#ENTRYPOINT while true; do sleep 1; ping postgresql_for_airflow; done
