{
 "title": "Train loss dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "train loss and chunking dataset progress",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_loss\",running=\"1\"}",
     "legendFormat": "train_loss {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"chunking_dataset_progress\",running=\"1\"}",
     "legendFormat": "chunking_dataset_progress {{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "histogram",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_loss\",running=\"1\"}",
     "legendFormat": "{{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "avg gradn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_avg_gradn\",running=\"1\"}",
     "legendFormat": "train {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"val_avg_gradn\",running=\"1\"}",
     "legendFormat": "val {{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "last loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_loss\",running=\"1\"}",
     "legendFormat": "{{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "Epoch Nr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"epoch_nr\",running=\"1\"}",
     "legendFormat": "{{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "mask error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_mask_error\",running=\"1\"}",
     "legendFormat": "train {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"val_mask_error\",running=\"1\"}",
     "legendFormat": "val {{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "EWMA train loss",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_loss_ewma\",running=\"1\"}",
     "legendFormat": "train {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"val_loss_ewma\",running=\"1\"}",
     "legendFormat": "val {{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "reconstructed set metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_reconstructed_set_avg\",running=\"1\"}",
     "legendFormat": "set_avg {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"train_reconstructed_set_std\",running=\"1\"}",
     "legendFormat": "set_std {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"train_reconstructed_mask_avg\",running=\"1\"}",
     "legendFormat": "mask_avg {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"train_reconstructed_mask_std\",running=\"1\"}",
     "legendFormat": "mask_std {{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "Train Epoch Elapsed Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_epoch_elapsed_time\",running=\"1\"}",
     "legendFormat": "{{rel_name}}"
    }
   ]
  },
  {
   "title": "Validation loss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"val_loss\",running=\"1\"}",
     "legendFormat": "{{rel_name}} {{run_id}}"
    }
   ]
  },
  {
   "title": "avg repr loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "mlflow_metric{metric_name=\"train_avg_repr_loss\",running=\"1\"}",
     "legendFormat": "train {{rel_name}} {{run_id}}"
    },
    {
     "expr": "mlflow_metric{metric_name=\"val_avg_repr_loss\",running=\"1\"}",
     "legendFormat": "val {{rel_name}} {{run_id}}"
    }
   ]
  }
 ]
}