services:
  statsd_exporter:
    build: statsd_exporter
    ports:
      - "127.0.3.1:9102:9102"
      - "127.0.3.1:9125:9125"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  prometheus:
    build: prometheus
    ports:
      - "127.0.3.1:9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  grafana:
    build: grafana
    ports:
      - "127.0.3.1:3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  mongo:
    build: mongo
    restart: unless-stopped
    user: "999:999"
    ports:
      - "127.0.3.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    command: --setParameter cursorTimeoutMillis=43200000 --setParameter globalConnPoolIdleTimeoutMinutes=720 --setParameter localLogicalSessionTimeoutMinutes=720 --setParameter connPoolMaxInUseConnsPerHost=5000 --setParameter connPoolMaxConnsPerHost=5000
    volumes:
      - "./mongo/db:/data/db:rw"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mlflow_ui:
    build: mlflow_ui
    ports:
      - "127.0.3.1:5000:5000"
    volumes:
      - "../mlruns:/mlruns"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  mlflow_exporter:
    build: mlflow_exporter
    ports:
      - "127.0.3.1:5500:5500"
    volumes:
      - "../mlruns:/mlruns"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  airflow_webserver:
    build: airflow_webserver
    hostname: airflow_webserver
    restart: unless-stopped
    depends_on:
      postgresql_for_airflow:
        condition: service_healthy
    ports:
      - "127.0.3.1:8080:8080"
    environment:
      - AIRFLOW_DATABASE_NAME=airflow_db
      - AIRFLOW_DATABASE_USERNAME=airflow_user
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_PG_PASSWORD}
      - AIRFLOW_DATABASE_HOST=postgresql_for_airflow
      - AIRFLOW_WEBSERVER_HOST=airflow_webserver
      - AIRFLOW_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_LOAD_EXAMPLES=no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  airflow_scheduler:
    build: airflow_scheduler
    hostname: airflow_scheduler
    restart: unless-stopped
    depends_on:
      postgresql_for_airflow:
        condition: service_healthy
    environment:
      - AIRFLOW_DATABASE_NAME=airflow_db
      - AIRFLOW_DATABASE_USERNAME=airflow_user
      - AIRFLOW_DATABASE_PASSWORD=${AIRFLOW_PG_PASSWORD}
      - AIRFLOW_DATABASE_HOST=postgresql_for_airflow
      - AIRFLOW_WEBSERVER_HOST=airflow_webserver
      - AIRFLOW_USERNAME=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_LOAD_EXAMPLES=no
    volumes:
      - "./airflow_scheduler/trained_models:/learning_sets/trained_models:rw"
      - "./airflow_scheduler/tmp_large_mp:/tmp/large_mp:rw"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  postgresql_for_airflow:
    build: postgresql_for_airflow
    hostname: postgresql_for_airflow
    restart: unless-stopped
    user: 0:0
    ports:
      - "127.0.3.1:5432:5432"
    environment:
      - POSTGRESQL_USERNAME=airflow_user
      - POSTGRESQL_PASSWORD=${AIRFLOW_PG_PASSWORD}
      - POSTGRESQL_POSTGRES_PASSWORD=${AIRFLOW_PG_PASSWORD}
      - POSTGRESQL_DATABASE=airflow_db
      - AIRFLOW_PG_HOST=postgresql_for_airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow_user"]
      interval: 5s
      timeout: 5s
      retries: 12
    volumes:
      - "./postgresql_for_airflow/volume:/bitnami/postgresql:rw"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
  loki:
    build: loki
    hostname: loki
    restart: unless-stopped
    ports:
      - "127.0.3.1:3100:3100"
    volumes:
      - "./loki/loki-config.yaml:/etc/loki/loki-config.yaml"
      - "./loki/data:/data/loki:rw"
      - "./loki/wal:/wal:rw"
    command: -config.file=/etc/loki/loki-config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  promtail:
    #container_name: promtail
    build: promtail
    hostname: promtail
    restart: unless-stopped
    volumes:
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml"
    command: -config.file=/etc/promtail/promtail-config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
