global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'statsd_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['statsd_exporter:9102']
  - job_name: 'mlflow_requests'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5000']
  - job_name: 'mlflow_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:5500']
