# suggestion on how to generate a password:
# tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo ''
# https://unix.stackexchange.com/questions/230673/how-to-generate-a-random-string

mongo_user: someuser
mongo_password: somepassword
mongo_host: somehost
mongo_port: 27017
mongo_db: learning_sets

vm_user: someuser
vm_host: somehost

airflow_pg_password: somepassword
airflow_user: someuser
airflow_password: somepassword
airflow_email: someuser@zimmerman.team

data_loader_num_workers: 4
models_dag_config_name: dspn_deepnarrow
models_dag_days_interval: 2
