experiment_name: activity_autoencoder_first
layers_width: 100
latent_dim: 20
sets_latent_dim: 4
activation_function: "ELU"
depth: 3
weight_decay: 1.0e-6
max_epochs: 1
batch_size: 16
divide_output_layer: True
latent_l1_norm: 10.0
cap_dataset: 3000
epoch_chunk_len: 100
optimizer: SGD
learning_rate: 5e-2
gradient_clip_val: 100
spec_name: activity_with_rels