experiment_name: dspn_first
layers_width: 48
latent_dim: 4
activation_function: "ELU"
depth: 3
weight_decay: 1.0e-4
max_epochs: 500
batch_size: 2048
divide_output_layer: True
latent_l1_norm: 10.0
max_set_size: 50
dspn_iter: 8
dspn_lr: 800
epoch_chunk_len: 2000
