experiment_name: dspn_first
layers_width: 48
latent_dim: 4
activation_function: "ELU"
depth: 15
weight_decay: 1.0e-6
max_epochs: 2000
batch_size: 2048
divide_output_layer: True
latent_l1_norm: 10.0
max_set_size: 25
dspn_iter: 15
dspn_lr: 0.1
cap_dataset: null
epoch_chunk_len: 1000
optimizer: SGD
learning_rate: 5e-2
gradient_clip_val: 100
dspn_loss_fn: mse_loss