experiment_name: dspn_first
layers_width: 64
latent_dim: 16
activation_function: "ELU"
depth: 3
weight_decay: 1.0e-4
max_epochs: 100
batch_size: 1024
divide_output_layer: True
latent_l1_norm: 10.0
max_set_size: 50
dspn_iter: 10
dspn_lr: 800
