experiment_name: dspn_first
layers_width: 48
latent_dim: 4
activation_function: "ELU"
depth: 15
weight_decay: 1.0e-6
max_epochs: 1500
batch_size: 2048
divide_output_layer: True
latent_l1_norm: 10.0
max_set_size: 25
dspn_iter: 8
dspn_lr: 800
cap_dataset: 3000
epoch_chunk_len: 30
optimizer: SGD
learning_rate: 5e-2
gradient_clip_val: 100
