experiment_name: dspn_first
layers_width: 16
latent_dim: 4
activation_function: "ELU"
depth: 2
weight_decay: 1.0e-4
max_epochs: 100
batch_size: 2048
divide_output_layer: True
latent_l1_norm: 10.0
max_set_size: 10
dspn_iter: 8
dspn_lr: 800
