experiment_name: autoencoder_baseline
layers_width: 3
bottleneck_width: 2
activation_function: "ELU"
depth: 5
weight_decay: 0
max_epochs: 2
rel_name: 'result'
batch_size: 1024
divide_output_layer: True
latent_l1_norm: 10.0