log_level: INFO

# suggestion on how to generate a password:
# tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo ''
# https://unix.stackexchange.com/questions/230673/how-to-generate-a-random-string

mongo_user: someuser
mongo_password: somepassword
mongo_host: somehost
mongo_port: 27017
mongo_db: learning_sets

vm_user: someuser
vm_host: somehost

airflow_pg_password: somepassword
airflow_user: someuser
airflow_password: somepassword
airflow_email: someuser@zimmerman.team
airflow_concurrency: 0012

download_page_size: 1000
download_max_pages: 3
download_max_set_size: 50

# data_loader_num_workers must be set to 0 to allow epoch chunking
data_loader_num_workers: 0

models_dag_config_name: dspn_deepnarrow
models_dag_days_interval: 2

trained_models_dirpath: trained_models/

log_step_elapsed_time: 60

# seems that one model being trained is using 4 CPU cores,
#   hence concurrency of 2 allows all of the 8 cores to be used
models_dag_training_tasks_concurrency: 2

# fraction of datapoints that go in a training test
# as opposed to a test set fraction, which ends up being 1.0-train_fraction
train_fraction: 0.9

# produce less tqdm logs
tame_tqdm: True
